### ISSUE TITLE
Setup swagger

### ISSUE THREAD

**Issue by dydyF05** [esgiprojetninja/express-pokemons#1]
https://www.npmjs.com/package/swagger-node-express

**Comment by grollec** [comment]
<img width="576" alt="capture d ecran 2018-03-08 a 10 33 37" src="https://user-images.githubusercontent.com/6169736/37144177-89d3c48c-22bd-11e8-969c-a5e931131938.png">
<img width="368" alt="capture d ecran 2018-03-08 a 10 33 45" src="https://user-images.githubusercontent.com/6169736/37144178-8a2bee8c-22bd-11e8-82dc-b20befe6ace5.png">

Ouais, on va prendre autre chose hein.
